apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/05-trigger.yaml

commonLabels:
  app: quarkus-env-config

# file .env is expected with the following variable
# GITHUB_ACCESS_TOKEN=...
#
secretGenerator:
- name: github-webhook-secret
  envs:
  - .env
  options:
    disableNameSuffixHash: true
